
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    restart: always
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    expose:
      - 5000
    volumes:
      - './app:/project'
    restart: always
    environment:
      TZ: Asia/Tokyo
